header:
  license:
    spdx-id: EPL-2.0
    copyright-owner: Data In Motion Consulting GmbH
    content: |
      This program and the accompanying materials are made available under the terms of the
      Eclipse Public License v2.0 which accompanies this distribution, and is available at
      http://www.eclipse.org/legal/epl-v20.html

    pattern: |
      This program and the accompanying materials are made available under the terms of the
      Eclipse Public License v2.0 which accompanies this distribution, and is available at
      http://www.eclipse.org/legal/epl-v20.html

  paths-ignore:
    - 'dist'
    - 'licenses'
    - '**/package-info.java'
    - '**/packageinfo'
    - '**/org/freshvanilla/**'
    - '**/permissions.perm'
    - '**/*.json'
    - '**/*.bnd'
    - '**/*.bndrun'
    - '**/*.xml'
    - '**/*.ecore'
    - '**/*.genmodel'
    - '**/*.md'
    - '**/*.MD'
    - '**/.classpath'
    - '**/.keep'
    - 'LICENSE'
    - 'Jenkinsfile'
    - 'NOTICE'
    - '.gitattributes'
    - '.github/**'
    - '.gitignore'
    - 'cnf/**'
    - 'gradle/**'
    - 'org.gecko.rest.bnd.template.project/**'
    - 'org.gecko.rest.bnd.template.workspace/**'
    - 'org.gecko.rest.jersey.index/**'
    - 'org.gecko.rest.jersey.tests/**'
    - '.gradle-wrapper/gradle-wrapper.properties'
    - '.licenserc.yaml'
    - '**/.project'
    - '**/.settings/**'
    - '**/*.prefs'
    - 'build.gradle'
    - 'gradle.properties'
    - 'gradlew'
    - 'gradlew.bat'
    - 'settings.gradle'
 
  comment: always
